spring:
  application:
    name: user-probider

  datasource:
    username: root
    password: ljw
    url: jdbc:mysql://localhost:3306/test05?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8866

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka